### PR TITLE
Fix post-fork documentation for Unicorn and Puma

### PR DESCRIPTION
**Pull request by htp**
The [documentation for Unicorn's after_fork](https://bogomips.org/unicorn/Unicorn/Configurator.html#method-i-after_fork) and the [documentation for Puma's on_worker_boot](https://www.rubydoc.info/github/puma/puma/Puma%2FConfiguration%2FDSL%3Aon_worker_boot) both suggest that the block supplied to each method is called _once per worker process_, and never for the master process.

My own quick and dirty tests corroborate the documentation. (Happy to supply gists if needed.)

In practice (with Puma, since we don't use Unicorn): the value passed to the `on_worker_boot` block is an `Integer`, which doesn't respond to `nr`- which makes for a confidence-uninspiring integrating experience.

Additionally, leaving `if worker_number.nr > 0` in place prevents the SDK from closing its TCP connections (which I understand to be non-persistent, since they're used for HTTP requests), causing sockets to be stuck in `CLOSE_WAIT`:

```
# lsof | grep CLOSE_WAIT
bundle       63           root    8u     IPv4            9126906       0t0      TCP c11949907d4d:52224->151.101.202.2:https (CLOSE_WAIT)
ruby-time    64    65     root    8u     IPv4            9126906       0t0      TCP c11949907d4d:52224->151.101.202.2:https (CLOSE_WAIT)
cluster.r    63    66     root    8u     IPv4            9126906       0t0      TCP c11949907d4d:52224->151.101.202.2:https (CLOSE_WAIT)
cluster.r    63    69     root    8u     IPv4            9126906       0t0      TCP c11949907d4d:52224->151.101.202.2:https (CLOSE_WAIT)
reactor.r    63    80     root    8u     IPv4            9126906       0t0      TCP c11949907d4d:52224->151.101.202.2:https (CLOSE_WAIT)
thread_po    63    81     root    8u     IPv4            9126906       0t0      TCP c11949907d4d:52224->151.101.202.2:https (CLOSE_WAIT)
thread_po    63    82     root    8u     IPv4            9126906       0t0      TCP c11949907d4d:52224->151.101.202.2:https (CLOSE_WAIT)
server.rb    63    83     root    8u     IPv4            9126906       0t0      TCP c11949907d4d:52224->151.101.202.2:https (CLOSE_WAIT)
impressio    63   254     root    8u     IPv4            9126906       0t0      TCP c11949907d4d:52224->151.101.202.2:https (CLOSE_WAIT)
thread_po    63  6291     root    8u     IPv4            9126906       0t0      TCP c11949907d4d:52224->151.101.202.2:https (CLOSE_WAIT)
thread_po    63  7474     root    8u     IPv4            9126906       0t0      TCP c11949907d4d:52224->151.101.202.2:https (CLOSE_WAIT)
thread_po    63  7510     root    8u     IPv4            9126906       0t0      TCP c11949907d4d:52224->151.101.202.2:https (CLOSE_WAIT)
thread_po    63  8234     root    8u     IPv4            9126906       0t0      TCP c11949907d4d:52224->151.101.202.2:https (CLOSE_WAIT)
thread_po    63  8351     root    8u     IPv4            9126906       0t0      TCP c11949907d4d:52224->151.101.202.2:https (CLOSE_WAIT)
thread_po    63  8397     root    8u     IPv4            9126906       0t0      TCP c11949907d4d:52224->151.101.202.2:https (CLOSE_WAIT)
thread_po    63 18606     root    8u     IPv4            9126906       0t0      TCP c11949907d4d:52224->151.101.202.2:https (CLOSE_WAIT)
thread_po    63 21911     root    8u     IPv4            9126906       0t0      TCP c11949907d4d:52224->151.101.202.2:https (CLOSE_WAIT)
bundle       67           root    8u     IPv4            9126906       0t0      TCP c11949907d4d:52224->151.101.202.2:https (CLOSE_WAIT)
ruby-time    67    70     root    8u     IPv4            9126906       0t0      TCP c11949907d4d:52224->151.101.202.2:https (CLOSE_WAIT)
cluster.r    67    77     root    8u     IPv4            9126906       0t0      TCP c11949907d4d:52224->151.101.202.2:https (CLOSE_WAIT)
split_sto    67    84     root    8u     IPv4            9126906       0t0      TCP c11949907d4d:52224->151.101.202.2:https (CLOSE_WAIT)
segment_s    67    85     root    8u     IPv4            9126906       0t0      TCP c11949907d4d:52224->151.101.202.2:https (CLOSE_WAIT)
metrics_s    67    86     root    8u     IPv4            9126906       0t0      TCP c11949907d4d:52224->151.101.202.2:https (CLOSE_WAIT)
impressio    67    87     root    8u     IPv4            9126906       0t0      TCP c11949907d4d:52224->151.101.202.2:https (CLOSE_WAIT)
events_se    67    88     root    8u     IPv4            9126906       0t0      TCP c11949907d4d:52224->151.101.202.2:https (CLOSE_WAIT)
cluster.r    67    89     root    8u     IPv4            9126906       0t0      TCP c11949907d4d:52224->151.101.202.2:https (CLOSE_WAIT)
reactor.r    67   137     root    8u     IPv4            9126906       0t0      TCP c11949907d4d:52224->151.101.202.2:https (CLOSE_WAIT)
thread_po    67   138     root    8u     IPv4            9126906       0t0      TCP c11949907d4d:52224->151.101.202.2:https (CLOSE_WAIT)
thread_po    67   140     root    8u     IPv4            9126906       0t0      TCP c11949907d4d:52224->151.101.202.2:https (CLOSE_WAIT)
server.rb    67   141     root    8u     IPv4            9126906       0t0      TCP c11949907d4d:52224->151.101.202.2:https (CLOSE_WAIT)
impressio    67   255     root    8u     IPv4            9126906       0t0      TCP c11949907d4d:52224->151.101.202.2:https (CLOSE_WAIT)
thread_po    67  7604     root    8u     IPv4            9126906       0t0      TCP c11949907d4d:52224->151.101.202.2:https (CLOSE_WAIT)
thread_po    67  7758     root    8u     IPv4            9126906       0t0      TCP c11949907d4d:52224->151.101.202.2:https (CLOSE_WAIT)
thread_po    67  7794     root    8u     IPv4            9126906       0t0      TCP c11949907d4d:52224->151.101.202.2:https (CLOSE_WAIT)
thread_po    67  7795     root    8u     IPv4            9126906       0t0      TCP c11949907d4d:52224->151.101.202.2:https (CLOSE_WAIT)
thread_po    67  7796     root    8u     IPv4            9126906       0t0      TCP c11949907d4d:52224->151.101.202.2:https (CLOSE_WAIT)
thread_po    67  8065     root    8u     IPv4            9126906       0t0      TCP c11949907d4d:52224->151.101.202.2:https (CLOSE_WAIT)
thread_po    67  8070     root    8u     IPv4            9126906       0t0      TCP c11949907d4d:52224->151.101.202.2:https (CLOSE_WAIT)
thread_po    67  8071     root    8u     IPv4            9126906       0t0      TCP c11949907d4d:52224->151.101.202.2:https (CLOSE_WAIT)
bundle       97           root    8u     IPv4            9126906       0t0      TCP c11949907d4d:52224->151.101.202.2:https (CLOSE_WAIT)
ruby-time    97    99     root    8u     IPv4            9126906       0t0      TCP c11949907d4d:52224->151.101.202.2:https (CLOSE_WAIT)
cluster.r    97   100     root    8u     IPv4            9126906       0t0      TCP c11949907d4d:52224->151.101.202.2:https (CLOSE_WAIT)
split_sto    97   101     root    8u     IPv4            9126906       0t0      TCP c11949907d4d:52224->151.101.202.2:https (CLOSE_WAIT)
segment_s    97   102     root    8u     IPv4            9126906       0t0      TCP c11949907d4d:52224->151.101.202.2:https (CLOSE_WAIT)
metrics_s    97   103     root    8u     IPv4            9126906       0t0      TCP c11949907d4d:52224->151.101.202.2:https (CLOSE_WAIT)
impressio    97   104     root    8u     IPv4            9126906       0t0      TCP c11949907d4d:52224->151.101.202.2:https (CLOSE_WAIT)
events_se    97   105     root    8u     IPv4            9126906       0t0      TCP c11949907d4d:52224->151.101.202.2:https (CLOSE_WAIT)
cluster.r    97   106     root    8u     IPv4            9126906       0t0      TCP c11949907d4d:52224->151.101.202.2:https (CLOSE_WAIT)
reactor.r    97   132     root    8u     IPv4            9126906       0t0      TCP c11949907d4d:52224->151.101.202.2:https (CLOSE_WAIT)
thread_po    97   133     root    8u     IPv4            9126906       0t0      TCP c11949907d4d:52224->151.101.202.2:https (CLOSE_WAIT)
thread_po    97   134     root    8u     IPv4            9126906       0t0      TCP c11949907d4d:52224->151.101.202.2:https (CLOSE_WAIT)
server.rb    97   135     root    8u     IPv4            9126906       0t0      TCP c11949907d4d:52224->151.101.202.2:https (CLOSE_WAIT)
impressio    97   253     root    8u     IPv4            9126906       0t0      TCP c11949907d4d:52224->151.101.202.2:https (CLOSE_WAIT)
thread_po    97  7579     root    8u     IPv4            9126906       0t0      TCP c11949907d4d:52224->151.101.202.2:https (CLOSE_WAIT)
thread_po    97  7584     root    8u     IPv4            9126906       0t0      TCP c11949907d4d:52224->151.101.202.2:https (CLOSE_WAIT)
thread_po    97  7625     root    8u     IPv4            9126906       0t0      TCP c11949907d4d:52224->151.101.202.2:https (CLOSE_WAIT)
thread_po    97  7642     root    8u     IPv4            9126906       0t0      TCP c11949907d4d:52224->151.101.202.2:https (CLOSE_WAIT)
thread_po    97  7805     root    8u     IPv4            9126906       0t0      TCP c11949907d4d:52224->151.101.202.2:https (CLOSE_WAIT)
thread_po    97  7807     root    8u     IPv4            9126906       0t0      TCP c11949907d4d:52224->151.101.202.2:https (CLOSE_WAIT)
thread_po    97  7878     root    8u     IPv4            9126906       0t0      TCP c11949907d4d:52224->151.101.202.2:https (CLOSE_WAIT)
thread_po    97 11577     root    8u     IPv4            9126906       0t0      TCP c11949907d4d:52224->151.101.202.2:https (CLOSE_WAIT)
bundle      112           root    8u     IPv4            9126906       0t0      TCP c11949907d4d:52224->151.101.202.2:https (CLOSE_WAIT)
ruby-time   112   116     root    8u     IPv4            9126906       0t0      TCP c11949907d4d:52224->151.101.202.2:https (CLOSE_WAIT)
cluster.r   112   117     root    8u     IPv4            9126906       0t0      TCP c11949907d4d:52224->151.101.202.2:https (CLOSE_WAIT)
split_sto   112   118     root    8u     IPv4            9126906       0t0      TCP c11949907d4d:52224->151.101.202.2:https (CLOSE_WAIT)
segment_s   112   119     root    8u     IPv4            9126906       0t0      TCP c11949907d4d:52224->151.101.202.2:https (CLOSE_WAIT)
metrics_s   112   120     root    8u     IPv4            9126906       0t0      TCP c11949907d4d:52224->151.101.202.2:https (CLOSE_WAIT)
impressio   112   121     root    8u     IPv4            9126906       0t0      TCP c11949907d4d:52224->151.101.202.2:https (CLOSE_WAIT)
events_se   112   122     root    8u     IPv4            9126906       0t0      TCP c11949907d4d:52224->151.101.202.2:https (CLOSE_WAIT)
cluster.r   112   123     root    8u     IPv4            9126906       0t0      TCP c11949907d4d:52224->151.101.202.2:https (CLOSE_WAIT)
reactor.r   112   146     root    8u     IPv4            9126906       0t0      TCP c11949907d4d:52224->151.101.202.2:https (CLOSE_WAIT)
thread_po   112   147     root    8u     IPv4            9126906       0t0      TCP c11949907d4d:52224->151.101.202.2:https (CLOSE_WAIT)
thread_po   112   148     root    8u     IPv4            9126906       0t0      TCP c11949907d4d:52224->151.101.202.2:https (CLOSE_WAIT)
server.rb   112   149     root    8u     IPv4            9126906       0t0      TCP c11949907d4d:52224->151.101.202.2:https (CLOSE_WAIT)
impressio   112   247     root    8u     IPv4            9126906       0t0      TCP c11949907d4d:52224->151.101.202.2:https (CLOSE_WAIT)
thread_po   112  4871     root    8u     IPv4            9126906       0t0      TCP c11949907d4d:52224->151.101.202.2:https (CLOSE_WAIT)
thread_po   112  7415     root    8u     IPv4            9126906       0t0      TCP c11949907d4d:52224->151.101.202.2:https (CLOSE_WAIT)
thread_po   112  7417     root    8u     IPv4            9126906       0t0      TCP c11949907d4d:52224->151.101.202.2:https (CLOSE_WAIT)
thread_po   112  7836     root    8u     IPv4            9126906       0t0      TCP c11949907d4d:52224->151.101.202.2:https (CLOSE_WAIT)
thread_po   112  7863     root    8u     IPv4            9126906       0t0      TCP c11949907d4d:52224->151.101.202.2:https (CLOSE_WAIT)
thread_po   112  8023     root    8u     IPv4            9126906       0t0      TCP c11949907d4d:52224->151.101.202.2:https (CLOSE_WAIT)
thread_po   112  8366     root    8u     IPv4            9126906       0t0      TCP c11949907d4d:52224->151.101.202.2:https (CLOSE_WAIT)
thread_po   112  8367     root    8u     IPv4            9126906       0t0      TCP c11949907d4d:52224->151.101.202.2:https (CLOSE_WAIT)
```

Removing `if worker_number.nr > 0` seems to do the job of allowing the SDK to close its end of finished TCP connections:

```
# lsof | grep CLOSE_WAIT
#
```

Again, I haven't thoroughly tested the Unicorn bits, but I suspect the behavior there is the same as it is for Puma.

### CODE REVIEW

**Comment by patricioe** [comment]
Thank you for sending this along. We'll take a look.

**Comment by htp** [comment]
You bet- let me know if there's anything I can do to help.

**Comment by patricioe** [comment]
@htp out of curiosity, is this causing any issue in your deployment?

**Comment by htp** [comment]
I'm not completely sure this is related, but it seems like it could be:

We have Split deployed such that our authorization service attaches split and treatment information to requests before passing the requests to downstream services. During our trial, I deleted the default `sample_feature` split, and created three new ones.

While testing, I noticed that every fourth request or so would come back with just the `sample_feature` split and its corresponding treatment; the intervening three-ish requests would have the three new splits and their corresponding treatments.

We have Puma configured to use 4 worker processes, so I suspect what happened was one worker (number 0) hadn't resumed its background threads and therefore couldn't poll for the new split definitions; whenever a request was routed to it, it would use its stale split definition and return stuff for the `sample_feature` split instead of for the newer splits.

I reported the issue to Kevin Li, but neither he nor the team were able to find anything suspicious-looking on your end of things.

**Comment by htp** [comment]
Following up, as this appears to be two separate issues:

1. The open (`CLOSE_WAIT`) connections listed in the `lsof` output appear to be carried over from the master process. (We're preloading our app with `preload_app!`.)

    If I drop this code block into my Puma config, all of the open connections disappear:

    ```
    before_fork do
      Split.instance_variable_get(:@config).threads.each { |_, t| t.exit }
    end
    ```

    This feels kind of hacky, though- it seems like `SplitFactory` wants a `stop!` method to match `start!` and `resume!`. Happy to provide changes in this or a separate PR- let me know which you'd prefer.

2. Using the above `before_fork`, if I do this (ignoring other Puma config):

    ```
    workers 1

    before_fork do
      Split.instance_variable_get(:@config).threads.each { |_, t| t.exit }
    end

    on_worker_boot do |n|
      ActiveSupport.on_load(:active_record) do
        ActiveRecord::Base.establish_connection
      end

      Split.resume! if n > 0
    end
    ```

    Then the SDK never returns treatments, and doesn't appear to make outgoing connections to the Split API.

    If I remove the `if n > 0` bit, the SDK behaves as expected.

In both cases, the `Split` constant referenced above is defined in an initializer like so:

```
Split = SplitIoClient::SplitFactoryBuilder.build(api_key, options)
```

**Comment by florrain** [comment]
Also seeing the same CLOSE_WAIT connections in a Rails 3 application running in Puma 3.10.0. Cluster mode, 5 workers having a single thread each.

The Split client is initialized in a Rails initializer, set in a $global_variable and resume! in the on_worker_boot. I also believe the connections opened when the client is created in the initializer from the master process are disconnected. The hosting application would need to explicitly disconnect those with a client.stop! or client.disconnect! in the before_fork block. 

Not sure if that would be compatible with the client architecture. Another solution could be to create the threads / connections lazily when the client needs to fetch its first treatment, meaning that the application is done preparing its state in the master process, the server did its forking and the current forked process is now serving requests.

```
$ ps aux
USER       PID %CPU %MEM    VSZ   RSS TTY      STAT START   TIME COMMAND
ruby         1  0.5  3.1 1155652 478936 ?      Ssl  15:10   0:16 puma 3.10.0 (tcp://0.0.0.0:3000) [app]
ruby        22  0.3  3.6 1767228 565496 ?      Sl   15:10   0:09 puma: cluster worker 0: 1 [app]
ruby        32  0.2  3.1 1635128 483588 ?      Sl   15:10   0:07 puma: cluster worker 1: 1 [app]
ruby        40  0.2  3.2 1635128 502184 ?      Sl   15:10   0:07 puma: cluster worker 2: 1 [app]
ruby        68  0.2  3.2 1635128 501780 ?      Sl   15:10   0:07 puma: cluster worker 3: 1 [app]
ruby        87  0.2  3.7 1766200 576204 ?      Sl   15:10   0:09 puma: cluster worker 4: 1 [app]
ruby      5460  0.0  0.0   4348  1600 ?        Ss   15:46   0:00 sh
ruby      7951  0.0  0.0  17516  2132 ?        R+   16:02   0:00 ps aux
```

```
$ lsof | grep CLOSE_WAIT
$ lsof | grep CLOSE_WAIT
ruby        22      ruby   12u  IPv4 973438718      0t0       TCP my-application-f7b697c64-cbdkn:47870->151.101.34.2:https (CLOSE_WAIT)
ruby        22      ruby   29u  IPv4 974286877      0t0       TCP my-application-f7b697c64-cbdkn:53722->151.101.202.2:https (CLOSE_WAIT)
ruby-time   22   24 ruby   12u  IPv4 973438718      0t0       TCP my-application-f7b697c64-cbdkn:47870->151.101.34.2:https (CLOSE_WAIT)
ruby-time   22   24 ruby   29u  IPv4 974286877      0t0       TCP my-application-f7b697c64-cbdkn:53722->151.101.202.2:https (CLOSE_WAIT)
ruby        22   25 ruby   12u  IPv4 973438718      0t0       TCP my-application-f7b697c64-cbdkn:47870->151.101.34.2:https (CLOSE_WAIT)
ruby        22   25 ruby   29u  IPv4 974286877      0t0       TCP my-application-f7b697c64-cbdkn:53722->151.101.202.2:https (CLOSE_WAIT)
ruby        22   26 ruby   12u  IPv4 973438718      0t0       TCP my-application-f7b697c64-cbdkn:47870->151.101.34.2:https (CLOSE_WAIT)
ruby        22   26 ruby   29u  IPv4 974286877      0t0       TCP my-application-f7b697c64-cbdkn:53722->151.101.202.2:https (CLOSE_WAIT)
ruby        22   27 ruby   12u  IPv4 973438718      0t0       TCP my-application-f7b697c64-cbdkn:47870->151.101.34.2:https (CLOSE_WAIT)
ruby        22   27 ruby   29u  IPv4 974286877      0t0       TCP my-application-f7b697c64-cbdkn:53722->151.101.202.2:https (CLOSE_WAIT)
ruby        22   29 ruby   12u  IPv4 973438718      0t0       TCP my-application-f7b697c64-cbdkn:47870->151.101.34.2:https (CLOSE_WAIT)
ruby        22   29 ruby   29u  IPv4 974286877      0t0       TCP my-application-f7b697c64-cbdkn:53722->151.101.202.2:https (CLOSE_WAIT)
ruby        22   30 ruby   12u  IPv4 973438718      0t0       TCP my-application-f7b697c64-cbdkn:47870->151.101.34.2:https (CLOSE_WAIT)
ruby        22   30 ruby   29u  IPv4 974286877      0t0       TCP my-application-f7b697c64-cbdkn:53722->151.101.202.2:https (CLOSE_WAIT)
ruby        22   31 ruby   12u  IPv4 973438718      0t0       TCP my-application-f7b697c64-cbdkn:47870->151.101.34.2:https (CLOSE_WAIT)
ruby        22   31 ruby   29u  IPv4 974286877      0t0       TCP my-application-f7b697c64-cbdkn:53722->151.101.202.2:https (CLOSE_WAIT)
ruby        22   38 ruby   12u  IPv4 973438718      0t0       TCP my-application-f7b697c64-cbdkn:47870->151.101.34.2:https (CLOSE_WAIT)
ruby        22   38 ruby   29u  IPv4 974286877      0t0       TCP my-application-f7b697c64-cbdkn:53722->151.101.202.2:https (CLOSE_WAIT)
ruby        22   39 ruby   12u  IPv4 973438718      0t0       TCP my-application-f7b697c64-cbdkn:47870->151.101.34.2:https (CLOSE_WAIT)
ruby        22   39 ruby   29u  IPv4 974286877      0t0       TCP my-application-f7b697c64-cbdkn:53722->151.101.202.2:https (CLOSE_WAIT)
ruby        22   52 ruby   12u  IPv4 973438718      0t0       TCP my-application-f7b697c64-cbdkn:47870->151.101.34.2:https (CLOSE_WAIT)
ruby        22   52 ruby   29u  IPv4 974286877      0t0       TCP my-application-f7b697c64-cbdkn:53722->151.101.202.2:https (CLOSE_WAIT)
ruby        22   54 ruby   12u  IPv4 973438718      0t0       TCP my-application-f7b697c64-cbdkn:47870->151.101.34.2:https (CLOSE_WAIT)
ruby        22   54 ruby   29u  IPv4 974286877      0t0       TCP my-application-f7b697c64-cbdkn:53722->151.101.202.2:https (CLOSE_WAIT)
ruby        22   56 ruby   12u  IPv4 973438718      0t0       TCP my-application-f7b697c64-cbdkn:47870->151.101.34.2:https (CLOSE_WAIT)
ruby        22   56 ruby   29u  IPv4 974286877      0t0       TCP my-application-f7b697c64-cbdkn:53722->151.101.202.2:https (CLOSE_WAIT)
ruby        22   58 ruby   12u  IPv4 973438718      0t0       TCP my-application-f7b697c64-cbdkn:47870->151.101.34.2:https (CLOSE_WAIT)
ruby        22   58 ruby   29u  IPv4 974286877      0t0       TCP my-application-f7b697c64-cbdkn:53722->151.101.202.2:https (CLOSE_WAIT)
ruby        22  163 ruby   12u  IPv4 973438718      0t0       TCP my-application-f7b697c64-cbdkn:47870->151.101.34.2:https (CLOSE_WAIT)
ruby        22  163 ruby   29u  IPv4 974286877      0t0       TCP my-application-f7b697c64-cbdkn:53722->151.101.202.2:https (CLOSE_WAIT)
ruby        22 4333 ruby   12u  IPv4 973438718      0t0       TCP my-application-f7b697c64-cbdkn:47870->151.101.34.2:https (CLOSE_WAIT)
ruby        22 4333 ruby   29u  IPv4 974286877      0t0       TCP my-application-f7b697c64-cbdkn:53722->151.101.202.2:https (CLOSE_WAIT)
ruby        32      ruby   12u  IPv4 973438718      0t0       TCP my-application-f7b697c64-cbdkn:47870->151.101.34.2:https (CLOSE_WAIT)
ruby-time   32   34 ruby   12u  IPv4 973438718      0t0       TCP my-application-f7b697c64-cbdkn:47870->151.101.34.2:https (CLOSE_WAIT)
ruby        32   35 ruby   12u  IPv4 973438718      0t0       TCP my-application-f7b697c64-cbdkn:47870->151.101.34.2:https (CLOSE_WAIT)
ruby        32   43 ruby   12u  IPv4 973438718      0t0       TCP my-application-f7b697c64-cbdkn:47870->151.101.34.2:https (CLOSE_WAIT)
ruby        32   45 ruby   12u  IPv4 973438718      0t0       TCP my-application-f7b697c64-cbdkn:47870->151.101.34.2:https (CLOSE_WAIT)
ruby        32   46 ruby   12u  IPv4 973438718      0t0       TCP my-application-f7b697c64-cbdkn:47870->151.101.34.2:https (CLOSE_WAIT)
ruby        32   47 ruby   12u  IPv4 973438718      0t0       TCP my-application-f7b697c64-cbdkn:47870->151.101.34.2:https (CLOSE_WAIT)
ruby        32   48 ruby   12u  IPv4 973438718      0t0       TCP my-application-f7b697c64-cbdkn:47870->151.101.34.2:https (CLOSE_WAIT)
ruby        32   49 ruby   12u  IPv4 973438718      0t0       TCP my-application-f7b697c64-cbdkn:47870->151.101.34.2:https (CLOSE_WAIT)
ruby        32   50 ruby   12u  IPv4 973438718      0t0       TCP my-application-f7b697c64-cbdkn:47870->151.101.34.2:https (CLOSE_WAIT)
ruby        32   51 ruby   12u  IPv4 973438718      0t0       TCP my-application-f7b697c64-cbdkn:47870->151.101.34.2:https (CLOSE_WAIT)
ruby        32   53 ruby   12u  IPv4 973438718      0t0       TCP my-application-f7b697c64-cbdkn:47870->151.101.34.2:https (CLOSE_WAIT)
ruby        32   55 ruby   12u  IPv4 973438718      0t0       TCP my-application-f7b697c64-cbdkn:47870->151.101.34.2:https (CLOSE_WAIT)
ruby        32   57 ruby   12u  IPv4 973438718      0t0       TCP my-application-f7b697c64-cbdkn:47870->151.101.34.2:https (CLOSE_WAIT)
ruby        32  490 ruby   12u  IPv4 973438718      0t0       TCP my-application-f7b697c64-cbdkn:47870->151.101.34.2:https (CLOSE_WAIT)
ruby        40      ruby   12u  IPv4 973438718      0t0       TCP my-application-f7b697c64-cbdkn:47870->151.101.34.2:https (CLOSE_WAIT)
ruby-time   40   42 ruby   12u  IPv4 973438718      0t0       TCP my-application-f7b697c64-cbdkn:47870->151.101.34.2:https (CLOSE_WAIT)
ruby        40   44 ruby   12u  IPv4 973438718      0t0       TCP my-application-f7b697c64-cbdkn:47870->151.101.34.2:https (CLOSE_WAIT)
ruby        40   62 ruby   12u  IPv4 973438718      0t0       TCP my-application-f7b697c64-cbdkn:47870->151.101.34.2:https (CLOSE_WAIT)
ruby        40   66 ruby   12u  IPv4 973438718      0t0       TCP my-application-f7b697c64-cbdkn:47870->151.101.34.2:https (CLOSE_WAIT)
ruby        40   67 ruby   12u  IPv4 973438718      0t0       TCP my-application-f7b697c64-cbdkn:47870->151.101.34.2:https (CLOSE_WAIT)
ruby        40   69 ruby   12u  IPv4 973438718      0t0       TCP my-application-f7b697c64-cbdkn:47870->151.101.34.2:https (CLOSE_WAIT)
ruby        40   76 ruby   12u  IPv4 973438718      0t0       TCP my-application-f7b697c64-cbdkn:47870->151.101.34.2:https (CLOSE_WAIT)
ruby        40   80 ruby   12u  IPv4 973438718      0t0       TCP my-application-f7b697c64-cbdkn:47870->151.101.34.2:https (CLOSE_WAIT)
ruby        40   81 ruby   12u  IPv4 973438718      0t0       TCP my-application-f7b697c64-cbdkn:47870->151.101.34.2:https (CLOSE_WAIT)
ruby        40   82 ruby   12u  IPv4 973438718      0t0       TCP my-application-f7b697c64-cbdkn:47870->151.101.34.2:https (CLOSE_WAIT)
ruby        40   83 ruby   12u  IPv4 973438718      0t0       TCP my-application-f7b697c64-cbdkn:47870->151.101.34.2:https (CLOSE_WAIT)
ruby        40   84 ruby   12u  IPv4 973438718      0t0       TCP my-application-f7b697c64-cbdkn:47870->151.101.34.2:https (CLOSE_WAIT)
ruby        40   85 ruby   12u  IPv4 973438718      0t0       TCP my-application-f7b697c64-cbdkn:47870->151.101.34.2:https (CLOSE_WAIT)
ruby        40  138 ruby   12u  IPv4 973438718      0t0       TCP my-application-f7b697c64-cbdkn:47870->151.101.34.2:https (CLOSE_WAIT)
ruby        68      ruby   12u  IPv4 973438718      0t0       TCP my-application-f7b697c64-cbdkn:47870->151.101.34.2:https (CLOSE_WAIT)
ruby-time   68   71 ruby   12u  IPv4 973438718      0t0       TCP my-application-f7b697c64-cbdkn:47870->151.101.34.2:https (CLOSE_WAIT)
ruby        68   72 ruby   12u  IPv4 973438718      0t0       TCP my-application-f7b697c64-cbdkn:47870->151.101.34.2:https (CLOSE_WAIT)
ruby        68   86 ruby   12u  IPv4 973438718      0t0       TCP my-application-f7b697c64-cbdkn:47870->151.101.34.2:https (CLOSE_WAIT)
ruby        68   89 ruby   12u  IPv4 973438718      0t0       TCP my-application-f7b697c64-cbdkn:47870->151.101.34.2:https (CLOSE_WAIT)
ruby        68   91 ruby   12u  IPv4 973438718      0t0       TCP my-application-f7b697c64-cbdkn:47870->151.101.34.2:https (CLOSE_WAIT)
ruby        68   92 ruby   12u  IPv4 973438718      0t0       TCP my-application-f7b697c64-cbdkn:47870->151.101.34.2:https (CLOSE_WAIT)
ruby        68   93 ruby   12u  IPv4 973438718      0t0       TCP my-application-f7b697c64-cbdkn:47870->151.101.34.2:https (CLOSE_WAIT)
ruby        68   97 ruby   12u  IPv4 973438718      0t0       TCP my-application-f7b697c64-cbdkn:47870->151.101.34.2:https (CLOSE_WAIT)
ruby        68   98 ruby   12u  IPv4 973438718      0t0       TCP my-application-f7b697c64-cbdkn:47870->151.101.34.2:https (CLOSE_WAIT)
ruby        68   99 ruby   12u  IPv4 973438718      0t0       TCP my-application-f7b697c64-cbdkn:47870->151.101.34.2:https (CLOSE_WAIT)
ruby        68  100 ruby   12u  IPv4 973438718      0t0       TCP my-application-f7b697c64-cbdkn:47870->151.101.34.2:https (CLOSE_WAIT)
ruby        68  101 ruby   12u  IPv4 973438718      0t0       TCP my-application-f7b697c64-cbdkn:47870->151.101.34.2:https (CLOSE_WAIT)
ruby        68  102 ruby   12u  IPv4 973438718      0t0       TCP my-application-f7b697c64-cbdkn:47870->151.101.34.2:https (CLOSE_WAIT)
ruby        68  127 ruby   12u  IPv4 973438718      0t0       TCP my-application-f7b697c64-cbdkn:47870->151.101.34.2:https (CLOSE_WAIT)
ruby        87      ruby   12u  IPv4 973438718      0t0       TCP my-application-f7b697c64-cbdkn:47870->151.101.34.2:https (CLOSE_WAIT)
ruby-time   87   90 ruby   12u  IPv4 973438718      0t0       TCP my-application-f7b697c64-cbdkn:47870->151.101.34.2:https (CLOSE_WAIT)
ruby        87   94 ruby   12u  IPv4 973438718      0t0       TCP my-application-f7b697c64-cbdkn:47870->151.101.34.2:https (CLOSE_WAIT)
ruby        87  104 ruby   12u  IPv4 973438718      0t0       TCP my-application-f7b697c64-cbdkn:47870->151.101.34.2:https (CLOSE_WAIT)
ruby        87  106 ruby   12u  IPv4 973438718      0t0       TCP my-application-f7b697c64-cbdkn:47870->151.101.34.2:https (CLOSE_WAIT)
ruby        87  107 ruby   12u  IPv4 973438718      0t0       TCP my-application-f7b697c64-cbdkn:47870->151.101.34.2:https (CLOSE_WAIT)
ruby        87  108 ruby   12u  IPv4 973438718      0t0       TCP my-application-f7b697c64-cbdkn:47870->151.101.34.2:https (CLOSE_WAIT)
ruby        87  109 ruby   12u  IPv4 973438718      0t0       TCP my-application-f7b697c64-cbdkn:47870->151.101.34.2:https (CLOSE_WAIT)
ruby        87  110 ruby   12u  IPv4 973438718      0t0       TCP my-application-f7b697c64-cbdkn:47870->151.101.34.2:https (CLOSE_WAIT)
ruby        87  111 ruby   12u  IPv4 973438718      0t0       TCP my-application-f7b697c64-cbdkn:47870->151.101.34.2:https (CLOSE_WAIT)
ruby        87  112 ruby   12u  IPv4 973438718      0t0       TCP my-application-f7b697c64-cbdkn:47870->151.101.34.2:https (CLOSE_WAIT)
ruby        87  113 ruby   12u  IPv4 973438718      0t0       TCP my-application-f7b697c64-cbdkn:47870->151.101.34.2:https (CLOSE_WAIT)
ruby        87  114 ruby   12u  IPv4 973438718      0t0       TCP my-application-f7b697c64-cbdkn:47870->151.101.34.2:https (CLOSE_WAIT)
ruby        87  115 ruby   12u  IPv4 973438718      0t0       TCP my-application-f7b697c64-cbdkn:47870->151.101.34.2:https (CLOSE_WAIT)
ruby        87  247 ruby   12u  IPv4 973438718      0t0       TCP my-application-f7b697c64-cbdkn:47870->151.101.34.2:https (CLOSE_WAIT)
```

My slimmed down config/puma.rb (without the MySQL disconnect! and reconnect)
```ruby
workers 5
threads 1, 1

preload_app!

rackup      DefaultRackup
port        ENV['PORT']     || 3000
environment ENV['RACK_ENV'] || 'production'

before_fork do
end

on_worker_boot do
  $split_factory.try(:resume!)
end
```

**Comment by SenhorCastor** [comment]
Hi, 

First of all, apologies for the delay.

We were able to replicate the findings from htp's and florrain's analysis. We executed similar tests, and ran into the same issues they reported.

We'll create new snippets based on the suggestions for Puma and Unicorn (specific for each AS), and update the SDK adding the stop! method, which will prevent connections to get stuck on CLOSE_WAIT, and also explicitly eliminate an instance of the SDK in a process that's not dealing with any requests. 

We'll link the new PRs here as soon as they're ready. Appreciate your help and suggestions!

**Comment by htp** [comment]
> First of all, apologies for the delay.

No worries- things come up :)

> We'll link the new PRs here as soon as they're ready. Appreciate your help and suggestions!

I'll keep an eye out- happy to have a look once they're ready!

**Comment by SenhorCastor** [comment]
We just released 5.0.1 with stop! and updated our documentation to reflect this PR.

Thanks a lot for the feedback!

Going to close this

**Pull request closed without merging**
