### PR TITLE
Support Redis 5.x

### PR DESCRIPTION
**Pull request by sliminas**
# Ruby SDK

## What did you accomplish?

Support Redis 5.x in the `.gemspec`

[Redis 5.0.0 release log](https://github.com/redis/redis-rb/blob/v5.0.0/CHANGELOG.md#500)

### CODE REVIEW

**Comment by sliminas** [comment]
@sanzmauro Is there any reason why Redis `5.x` is not supported?
It's sad to see that I need to downgrade the split client from `8.x` to `7.x` when dependabot schedules a Redis `5.x` update. :cry: 

---

image

**Comment by sanzmauro** [comment]
HI @sliminas I am closing the PR because I included these changes here: [release candidate](https://rubygems.org/gems/splitclient-rb/versions/8.1.1.pre.rc2).
I am going to release a stable version next week. 

Apology for the inconvenience.

Regards,
Mauro

**Comment by sliminas** [comment]
Hi @sanzmauro,
No worries, and thank you for working on this!
:+1: :1st_place_medal:

**Comment by sanzmauro** [comment]
Hi @sliminas,
[8.1.1](https://rubygems.org/gems/splitclient-rb/versions/8.1.1) has been released. 🚀 

Regards,
Mauro

**Pull request closed without merging**
